// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2) {
  return window['go']['main']['App']['AddUser'](arg1, arg2);
}

export function GetActiveConnections() {
  return window['go']['main']['App']['GetActiveConnections']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLocalIPAddresses() {
  return window['go']['main']['App']['GetLocalIPAddresses']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTrayState() {
  return window['go']['main']['App']['GetTrayState']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoveUser(arg1) {
  return window['go']['main']['App']['RemoveUser'](arg1);
}

export function ResetUserPassword(arg1, arg2) {
  return window['go']['main']['App']['ResetUserPassword'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAuthEnabled(arg1) {
  return window['go']['main']['App']['SetAuthEnabled'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
